apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: presys-frontend
  namespace: pensjon-saksbehandling
  labels:
    team: pensjon-saksbehandling
  annotations:
    nginx.ingress.kubernetes.io/client_header_buffer_size: "16k"
    nginx.ingress.kubernetes.io/large_client_header_buffers: "4 32k"
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://presys-frontend.nais.preprod.local"
    - "https://presys-frontend.dev.adeo.no"
  replicas:
    min: 1
    max: 1
