apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: presys
  namespace: pensjon-saksbehandling
  labels:
    team: pensjon-saksbehandling
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://presys.nais.adeo.no"
  liveness:
    path: isAlive
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 20
  readiness:
    path: isReady
    initialDelay: 60
    periodSeconds: 10
    failureThreshold: 20
  vault:
    enabled: true
    paths:
      - mountPath: /secrets/oracle/creds
        kvPath: oracle/data/prod/creds/presys-user
      - mountPath: /secrets/oracle/config
        kvPath: oracle/data/prod/config/presys
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 512Mi
  prometheus:
    enabled: true
