FROM navikt/java:8

ENV LDAP_URL="" \
    LDAP_DOMAIN="" \
    LDAP_BASEDN="" \
    JWT_PASSWORD="" \
    PRESYSDB_URL="" \
    PRESYSDB_USERNAME="" \
    PRESYSDB_PASSWORD=""

ENV JAVA_OPTS -Dspring.profiles.active=nais