export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';

export const SAKSBEHANDLER_RECEIVED = 'SAKSBEHANDLER_RECEIVED';

export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_RESULT_RECEIVED = 'SEARCH_RESULT_RECEIVED';
export const SELECT_FAGSAK = 'SELECT_FAGSAK';

export const BEHANDLINGER_FETCH_STARTED = 'BEHANDLINGER_FETCH_STARTED';
export const BEHANDLINGER_RECEIVED = 'BEHANDLINGER_RECEIVED';
export const SELECT_BEHANDLING = 'SELECT_BEHANDLING';
export const TOGGLE_DISPLAYED_BEHANDLINGER = 'TOGGLE_DISPLAYED_BEHANDLINGER';

export const SET_BEHANDLINGSPUNKTER = 'SET_BEHANDLINGSPUNKTER';
export const SET_SELECTED_BEHANDLINGSPUNKT = 'SET_SELECTED_BEHANDLINGSPUNKT';

export const SET_BEHANDLINGSPUNKT_FORM_DATA = 'SET_BEHANDLINGSPUNKT_FORM_DATA';

export const SET_MODEL = 'SET_MODEL';
export const RESET_MODEL = 'RESET';
export const SET_PREVIOUS_MODEL = 'SET_PREVIOUS_MODEL';
export const SHOW_FORM_ERRORS = 'SHOW_FORM_ERRORS';
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const FORM_SAVE_STARTED = 'FORM_SAVE_STARTED';
export const FORM_POST_SUCCESS = 'FORM_POST_SUCCESS';

export const DOCUMENTS_FETCH_STARTED = 'DOCUMENTS_FETCH_STARTED';
export const DOCUMENTS_RECEIVED = 'DOCUMENTS_RECEIVED';
export const DOCUMENT_FETCH_STARTED = 'DOCUMENT_FETCH_STARTED';
export const DOCUMENT_RECEIVED = 'DOCUMENT_RECEIVED';
