export const SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';

export const SAKSBEHANDLER_RECEIVED = 'SAKSBEHANDLER_RECEIVED';

export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_RESULT_RECEIVED = 'SEARCH_RESULT_RECEIVED';

export const SET_MODEL = 'SET_MODEL';
export const RESET_MODEL = 'RESET';
export const SET_PREVIOUS_MODEL = 'SET_PREVIOUS_MODEL';
export const SHOW_FORM_ERRORS = 'SHOW_FORM_ERRORS';
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const FORM_SAVE_STARTED = 'FORM_SAVE_STARTED';
export const FORM_POST_SUCCESS = 'FORM_POST_SUCCESS';

export const PERSON_FETCH_STARTED = 'PERSON_FETCH_STARTED';
export const PERSON_FETCH_FAILED = 'PERSON_FETCH_FAILED';
export const PERSON_RECEIVED = 'PERSON_RECEIVED';


export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
