name: Frontend build, release and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}/presys-frontend

jobs:
  build:
    permissions:
      contents: "read"
      packages: "write"
      id-token: "write"  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Build
        working-directory: ./klient/
        run: |
          npm install
          npm test

      - uses: nais/docker-build-push@v0
        id: docker-push
        with:
          docker_context: klient
          team: pensjon-saksbehandling

      - name: Deploy to dev-fss
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: .nais/klient-dev.yaml
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}

      - name: Deploy to prod-fss
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: .nais/klient-prod.yaml
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}
