name: Frontend build, release and deploy

on: push

env:
  FRONTEND_IMAGE: ghcr.io/${{ github.repository }}/presys-frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Build
        working-directory: ./klient/
        run: |
          npm install
          npm test

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: x-access-token
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docker tag
        run: |
          echo "VERSION=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build docker image
        run: docker build -t ${FRONTEND_IMAGE}:${VERSION} klient
        env:
          BACKEND_IMAGE: ${{ env.FRONTEND_IMAGE }}
          VERSION: ${{ env.VERSION }}

      - name: Release docker image
        run: docker push ${FRONTEND_IMAGE}:${VERSION}
        env:
          BACKEND_IMAGE: ${{ env.FRONTEND_IMAGE }}
          VERSION: ${{ env.VERSION }}
